config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root "customers#index"
  #get "/", to: "customers#index"
  get "customers/missing_email", to: "customers#missing_email"
  get "customers/alphabetized", to: "customers#alphabetized"

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
  
  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "encrypted_password", "id", "id_value", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord
    def self.ransackable_attributes(auth_object = nil)
        ["created_at", "email_address", "full_name", "id", "id_value", "notes", "phone_number", "updated_at"]
    end

    def self.ransackable_associations(auth_object = nil)
        ["image_attachment", "image_blob"]
    end

    has_one_attached :image

    validates :full_name, presence: true
    validates :phone_number, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
    def index
        @customers = Customer.all
    end

    def alphabetized
        @customers = Customer.order(:full_name)
    end

    def missing_email
        @customers = Customer.where(email_address: [nil, ''])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_customer.html.erb
<!-- Partial for customer -->
<div class="customer-card">
  <%= image_tag customer.image.attached? ? url_for(customer.image) : 'default_image_path.jpg', class: 'w-full' %>
  <div class="px-6 py-4">
    <div class="font-bold text-xl mb-6"><%= customer.full_name %></div>
    <p class="text-gray-700 text-base pb-2">
      Phone: <%= customer.phone_number %>
    </p>
    <p class="text-gray-700 text-base pb-2">
      Email: <%= customer.email_address.present? ? customer.email_address : 'N/A' %>
    </p>
    <p class="text-gray-700 text-base pb-2">
      Notes: <%= customer.notes %>
    </p>
  </div>
</div>

app/views/customers/alphabetized.html.erb
<div class="flex flex-col items-start">
    <h1 class="text-3xl font-bold mb-6">Alphabetized Customers</h1>
    <div class="mb-4">
    <%= link_to 'All Customers', root_path, class: 'text-blue-500 hover:underline' %> |
    <%= link_to 'Customers with Missing Emails', customers_missing_email_path, class: 'text-blue-500 hover:underline' %>
    </div>
    <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
    <%= render partial: 'customer', collection: @customers %>
    </div>
</div>

app/views/customers/index.html.erb
<!-- Index to render partial-->
<div class="flex flex-col items-start">
    <h1 class="text-3xl font-bold mb-6">All Customers</h1>
    <div class="mb-4 text-blue-500">
        <%= link_to "Alphabetized Customers", customers_alphabetized_path, class: "text-green-500 hover:underline" %> |
        <%= link_to "Customers with Missing Emails", customers_missing_email_path, class: "text-blue-500 hover:underline" %>
    </div>
    <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
    <%= render partial: 'customer', collection: @customers %>
    </div>
</div>

app/views/customers/missing_email.html.erb
<div class="flex flex-col items-start">
    <h1 class="text-3xl font-bold mb-6">Customers with Missing Emails</h1>
    <div class="mb-4">
    <%= link_to 'All Customers', root_path, class: 'text-blue-500 hover:underline' %> |
    <%= link_to 'Alphabetized Customers', customers_alphabetized_path, class: 'text-blue-500 hover:underline' %>
    </div>
    <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
    <%= render partial: 'customer', collection: @customers %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CRM U6</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!--<%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>-->

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-2 px-5 flex flex-col items-center">
      <%= yield %>
    </main>
  </body>
</html>